// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchedulerAgentSupervisor.WebApi.Persistence;

#nullable disable

namespace SchedulerAgentSupervisor.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220513204501_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SchedulerAgentSupervisor.WebApi.Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("DATE");

                    b.Property<int>("IntervalInDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeSpan>("TimeOfDay")
                        .HasColumnType("TIME");

                    b.HasKey("Id");

                    b.HasIndex("TaskName")
                        .IsUnique();

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("SchedulerAgentSupervisor.WebApi.Domain.Schedule", b =>
                {
                    b.OwnsMany("SchedulerAgentSupervisor.WebApi.Domain.ScheduleRun", "History", b1 =>
                        {
                            b1.Property<string>("TaskName")
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<Guid>("CorrelationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<Guid>("ScheduleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTimeOffset>("Time")
                                .HasColumnType("datetimeoffset");

                            b1.HasKey("TaskName", "CorrelationId", "State");

                            b1.HasIndex("ScheduleId");

                            b1.ToTable("ScheduleRuns", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ScheduleId");
                        });

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
