GET https://localhost:5001/api/test/generate
Accept: application/json

###

GET https://localhost:5001/api/test/verify
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MjEwNjA4NDgsImV4cCI6MTYyMTA3MTY0OCwiaXNzIjoid2ViYXBpIiwiYXVkIjoid2ViYXBpIn0.ovIF7IacWJ0TjrwFrkmw-DuwdaRau58iY1lGzC038L_4E1Gz7deObwTfrhJl7AzCRiguEkXKsXbe4-WMXHyvUe9f8MI8-NmKKNu9Jx8A-7apdvNXvSmpW6lJRVABv0ojstMku-BGdNk2HsZHLqHfJepCgTDtK4HLLGsBAhiVS7m-zJ5i3oyj7HWSk7-AnRQWXkeJ7GRzkB7xHjh8YkXmDDtF_jQFnItD63JmQvOHE_UZXvlAyRyphetOA20vEQLwQ1OcZbSWEtVN4HIkG1hDMVpQdZ2Df85YG4EoAtx4RXeuN6B5dRloG1ltg034t6iQPtmXFv08nur8jyjSBy6v6A

###

GET https://localhost:5001/api/test/generatesymmetric
Accept: application/json

###

GET https://localhost:5001/api/test/verifysymmetric
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MjEwNjI3NjQsImV4cCI6MTYyMTA3MzU2NCwiaXNzIjoid2ViYXBpIiwiYXVkIjoid2ViYXBpIn0.KMAivVjzvsAXa65av999vFWrArxGVv96RCPkOhSPbfY

###