GET https://localhost:5001/api/test/Generate
Accept: application/json

###

GET https://localhost:5001/api/test/verify
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MjEzMzMwNzUsImV4cCI6MTYyMTM0Mzg3NSwiaXNzIjoid2ViYXBpIiwiYXVkIjoid2ViYXBpIn0.xUWDIBKxc6yCi4D_jYy7aw32OFAp6G3RAF7btqj02gki1kuvUF7_hZF6_nmDJjGM_nOX_L7HAUu6rah3cIoWjDvsBqN6zTlVonns2AD41pajwSHc3cprD4KY3dwrTZodS660ec1fgCq052depXhkEq9X_dq8OlWJGsfWAVddtsy7JmkJzClNyz3ly8q5rXcZOUmZzBGY5RrvS-SzYumSFP-MtNL54CBUY5s1byRaggqEIcLStNTJ9OcZnhcYG4ly8XH2IgxMZvzuhCRpcdBCByEtv-2A8IZzmriJq7C5RqJVbWMVwbMpF5UaGgFCPN7tkxE5sv8szot4oGn78gGMtQ

###

GET https://localhost:5001/api/test/generatesymmetric
Accept: application/json

###

GET https://localhost:5001/api/test/verifysymmetric
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MjEwNjI3NjQsImV4cCI6MTYyMTA3MzU2NCwiaXNzIjoid2ViYXBpIiwiYXVkIjoid2ViYXBpIn0.KMAivVjzvsAXa65av999vFWrArxGVv96RCPkOhSPbfY

###