GET https://localhost:5001/api/test/generate
Accept: application/json

###
GET https://localhost:5001/api/test
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2MjA3NDA5MTEsImV4cCI6MTYyMDc1ODkxMSwiaXNzIjoid2ViYXBpIiwiYXVkIjoid2ViYXBpIn0.q1UzNEjrdJiFIZQOjcv6rUMCkRE7HctgRkCiDb51neKASX1UAW99ZdRs7T8ZkBvGLZsClUioj5b_fAfRRKbNnWXw02bR0thNtp_btCrLEP7FwF7jxYC8VOcTiI8AquUMEvfxlVIO5p6KOABM118SQsSr6hM5HbNU7-8XRx7ru5oU-tjheTkBxk9PmPIPc4M9Y4Ah_lunS6-j5-9oOtP2xhKhRos3it3J4Guc6jIYeykRmaN06qVA7fRoY_HHekpS-ae9x9J0cwHR8sPl8XCGomvfEWj5uj9q_OOiwvNqMSil9RzTEM6hkDy29EuEtkOdpULh5xeHb3vUy-gzvKe1aQ

###


