GET https://localhost:5001/api/users/login/1
Accept: application/json

###

GET https://localhost:5001/api/users
Accept: application/json
Authorization: Bearer insert_auth

###

GET https://localhost:5001/api/Users/1/view/profileimage
Accept: image/jpeg

###

GET https://localhost:5001/api/articles
Accept: application/csv

###


