@address = http://localhost:5101

POST {{address}}/users/create
Accept: application/json
Content-Type: application/json

{
  "username": "Nix Piek"
}

###

POST {{address}}/users/0f1977f6-ff29-4312-bda8-7f13e6271b07/checkin
Accept: application/json
Content-Type: application/json

{
  "text": "More good content."
}

###

GET {{address}}/users/0f1977f6-ff29-4312-bda8-7f13e6271b07/checkins
Accept: application/json

###

GET {{address}}/users/0f1977f6-ff29-4312-bda8-7f13e6271b07/materialized/checkins
Accept: application/json