@address = http://localhost:5101

POST {{address}}/users/create
Accept: application/json
Content-Type: application/json

{
  "username": "Nix Piek"
}

###

POST {{address}}/users/8609a75d-83fe-4c74-83be-0c8dbaf67a67/checkin
Accept: application/json
Content-Type: application/json

{
  "text": "More good content."
}

###

GET {{address}}/users/8609a75d-83fe-4c74-83be-0c8dbaf67a67/checkins
Accept: application/json

###

GET {{address}}/users/8609a75d-83fe-4c74-83be-0c8dbaf67a67/materialized/checkins
Accept: application/json